### ISSUE TITLE
Add some navigation links (like previous or next chapters)

### ISSUE THREAD

**Issue by antoinentl** [electricbookworks/electric-book-workflow#48]
To facilitate the reading, it would be necessary to add some navigation links between the parts and the chapters, like "← previous chapter" or "next chapter →".

If you want to do this, and do not do it manually, you can use the "nav" part of the file `_data/meta.yml`.

**Comment by arthurattwell** [comment]
Thanks, @antoinentl – definitely, this is a big missing feature. I have an issue for this on the template repo [here](https://github.com/electricbookworks/electric-book/issues/51). We're aiming to build this into the Jekyll template in the next couple of months, because we need it for a client project.

We're also working on ways to break up very long pages/chapters into accordion-style navigation using Javascript.

**Comment by antoinentl** [comment]
Thanks for this information @arthurattwell! I build a navigation system with Jekyll on this project: [https://www.010101book.net/](https://www.010101book.net/), you can look at [https://github.com/antoinentl/010101book.net/blob/master/_includes/nav.html](https://github.com/antoinentl/010101book.net/blob/master/_includes/nav.html) but I think something more clever is possible.

**Comment by arthurattwell** [comment]
This issue was moved to electricbookworks/electric-book#153
